name: AWS EC2 Self Hosted Runner
description: Create a self hosted runner on AWS EC2
author: Kepler Authors

# Define your inputs here.
inputs:
  action: 
    description: 'The action to perform. One of create, unregister, terminate'
    required: true
  github_token:
    description: 'The GitHub token to use'
    required: false
  aws_access_key_id:
    description: 'The AWS access key id to use'
    required: false
  aws_secret_access_key:
    description: 'The AWS secret access key to use'
    required: false
  security_group_id:
    description: 'The AWS security group id to use'
    required: false
  aws_region:
    description: 'The AWS region to use'
    required: false
  github_repo:
    description: 'The GitHub repo to use'
    required: false
  ami_id:
    description: 'The AMI ID to use for the EC2 instance'
    required: false
  key_name:
    description: 'The key name to use for the EC2 instance'
    required: false
  root_volume_size:
    description: 'The root volume size to use for the EC2 instance'
    required: false
  instance_type:
    description: 'The instance type to use for the EC2 instance'
    required: false
  create_s3_bucket:
    description: 'Create an S3 bucket to store the runner state'
    required: false
  spot_instance_only:
    description: 'Only use spot instances'
    required: false
  instance_id:
    description: 'The instance id to use during terminate action'
    required: false
  runner_name:
    description: 'The name of the self hosted runner during unregister action'
    required: false
  bucket_name:
    description: 'The name of the S3 bucket (if created) to use during terminate action'
    required: false
  auto_terminate_hours:
    description: 'The number of hours to wait before terminating the instance'
    required: false

# Define your outputs here.
outputs:
  instance_id:
    description: The AWS EC2 instance id
  instance_ip:
    description: The AWS EC2 instance ip
  runner_name:
    description: The name of the self hosted runner
  bucket_name:
    description: The name of the S3 bucket (if created)
  termination_time:
    description: The time the instance will be automatically terminated (if enabled)

runs:
  using: docker
  image: Dockerfile
